services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - sandbox-network

  jaeger-allinone:
    image: jaegertracing/all-in-one:1.25
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 16686:16686
      - 14268:14268
    networks:
      - sandbox-network

  producer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8080
      - 5005:5005
    image: vsanyc/rabbitmq-sandbox:0.1
    environment:
      - CONNECTION_TYPE=producer
      - APPLICATION_ID=producer-1
      - SPRING_RABBITMQ_HOST=rabbitmq
      - REMOTE_URL=http://consumer:8080/simple-request
      - SPRING_APPLICATION_NAME=producerApp
      - OPENTRACING_JAEGER_HTTP_SENDER_URL=http://jaeger-allinone:14268/api/traces
      - JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,address=*:5005,server=y,suspend=n"
    depends_on:
      - consumer
      - rabbitmq
    networks:
      - sandbox-network

  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8082:8080
      - 5006:5005
    image: vsanyc/rabbitmq-sandbox:0.1
    environment:
      - CONNECTION_TYPE=consumer
      - APPLICATION_ID=consumer-1
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_APPLICATION_NAME=consumerApp
      - OPENTRACING_JAEGER_HTTP_SENDER_URL=http://jaeger-allinone:14268/api/traces
      - JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,address=*:5005,server=y,suspend=n"
    depends_on:
      - rabbitmq
    networks:
      - sandbox-network

networks:
  sandbox-network:
    driver: bridge
